# Generated by Django 4.2.4 on 2023-08-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscriber_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='received_fact_ids',
            field=models.ManyToManyField(related_name='received_by', to='main.fact'),
        ),
    ]
